import React from 'react';
import { AlertCircle, AlertTriangle, CheckSquare, FileText, ShieldAlert, ShieldX } from 'lucide-react';

export const RiskDisclosurePage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-10 pb-16">
      {/* Header */}
      <div className="border-b border-slate-800 pb-6 space-y-2">
        <div className="flex items-center space-x-2 text-xs font-mono text-amber-400 font-semibold uppercase tracking-wider">
          <ShieldAlert className="w-4 h-4" />
          <span>Legal & Research Notice</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
          Risk Disclosure & Terms of Research
        </h1>
        <p className="text-sm text-slate-300 leading-relaxed">
          Please read this complete disclosure carefully before utilizing the Candle Probability Lab platform.
        </p>
      </div>

      {/* Main Alert Box */}
      <div className="bg-rose-950/20 border border-rose-500/40 rounded-2xl p-6 space-y-3">
        <div className="flex items-center space-x-2 text-rose-300 font-bold font-mono text-sm">
          <AlertTriangle className="w-5 h-5 text-rose-400" />
          <span>HIGH-RISK WARNING: TRADING CARRIES SEVERE RISK OF CAPITAL LOSS</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          Trading spot cryptocurrencies, derivatives, equities, or other financial instruments involves substantial risk of loss and is not suitable for every individual. You could lose all or more of your initial investment. Never trade with capital that you cannot afford to lose.
        </p>
      </div>

      {/* Core Disclosure Statements */}
      <div className="space-y-6">
        {/* 1. Predictions Can Be Wrong */}
        <div className="bg-[#0E131F] border border-slate-800 rounded-xl p-5 space-y-2">
          <h3 className="text-base font-bold text-white font-mono flex items-center space-x-2">
            <span className="text-cyan-400">1.</span>
            <span>Probability Models Can and Will Be Incorrect</span>
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            The predicted +1 and +2 candles generated by this platform represent experimental mathematical probabilities based on historical technical indicator agreement. Market movements are influenced by complex variables that no technical indicator can fully anticipate. Predictions are frequently wrong.
          </p>
        </div>

        {/* 2. No Guaranteed Future Candles or Accuracy */}
        <div className="bg-[#0E131F] border border-slate-800 rounded-xl p-5 space-y-2">
          <h3 className="text-base font-bold text-white font-mono flex items-center space-x-2">
            <span className="text-cyan-400">2.</span>
            <span>No Guarantee of Accuracy or Profit</span>
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Candle Probability Lab explicitly disclaims any representation, warranty, or guarantee regarding the accuracy, reliability, or profitability of its predictions. Confidence scores (50% to 80%) indicate model agreement, never probability of financial gain.
          </p>
        </div>

        {/* 3. Not Financial or Investment Advice */}
        <div className="bg-[#0E131F] border border-slate-800 rounded-xl p-5 space-y-2">
          <h3 className="text-base font-bold text-white font-mono flex items-center space-x-2">
            <span className="text-cyan-400">3.</span>
            <span>Not Financial or Investment Advice</span>
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            All content, data, signals, and charts provided on this platform are for educational, quantitative research, and informational purposes only. Nothing on this website constitutes financial, legal, tax, or investment advice. You must consult a qualified licensed financial advisor before making any financial decisions.
          </p>
        </div>

        {/* 4. Past Performance Disclaimer */}
        <div className="bg-[#0E131F] border border-slate-800 rounded-xl p-5 space-y-2">
          <h3 className="text-base font-bold text-white font-mono flex items-center space-x-2">
            <span className="text-cyan-400">4.</span>
            <span>Historical Performance Does Not Guarantee Future Outcomes</span>
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Historical accuracy metrics shown on the Performance page reflect past candle evaluations. Past success is no indication or guarantee of future accuracy in different market regimes or conditions.
          </p>
        </div>

        {/* 5. Non-Broker & No Trade Execution */}
        <div className="bg-[#0E131F] border border-slate-800 rounded-xl p-5 space-y-2">
          <h3 className="text-base font-bold text-white font-mono flex items-center space-x-2">
            <span className="text-cyan-400">5.</span>
            <span>Platform Does Not Execute Trades or Hold Funds</span>
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Candle Probability Lab is strictly an analytics dashboard. It is not an exchange, not a broker, and not a trading platform. It does not accept deposits, execute orders, or connect to private trading accounts.
          </p>
        </div>
      </div>
    </div>
  );
};
